name: Dart Analyzer

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Dart Analyze
        run: dart analyze > dart_analyze.txt || true
        
      - name: Dart Analyze to SARIF
        uses: advanced-security/dart-analyzer-sarif@main
        with:
          input: dart_analyze.txt
          output: dart_analyze.sarif
          
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: dart_analyze.sarif
