
name: Flutter Unit Tests

on:
  pull_request: {}

jobs:
  tests:

    permissions:
      # For actions/checkout to fetch code
      contents: read
      # For github/codeql-action/upload-sarif to upload SARIF results
      security-events: write
      # Only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      actions: read

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/flutter-action
      - name: Setup Flutter
        # SHA for v2.10.0
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
          cache: true

      - name: Run Flutter Tests
        run: flutter test