
name: Flutter Unit Tests

on:
  pull_request:

jobs:
  tests:

    permissions:
      # For actions/checkout to fetch code
      contents: read
      # For github/codeql-action/upload-sarif to upload SARIF results
      security-events: write
      # Only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      actions: read

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Run Flutter Tests
        run: flutter test